#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef SENSIBILL_SWIFT_H
#define SENSIBILL_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Sensibill",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)





/// Allows to subscribe to Sensibill SDK events and user actions
SWIFT_CLASS_NAMED("Analytics")
@interface SBLAnalytics : NSObject
/// A singleton instance of the Analytics
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SBLAnalytics * _Nonnull shared;)
+ (SBLAnalytics * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface SBLAnalytics (SWIFT_EXTENSION(Sensibill))
@end

@class NSString;

SWIFT_CLASS_NAMED("TrackingEvent")
@interface SBLAnalyticsTrackingEvent : NSObject
/// All event fields as a dictionary.
/// The dictionary will contain <code>TrackingEvent.Fields</code>, as well as any other custom properties set for the event.
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull asDictionary;
/// The initializer. Automatically sets the <code>SensibillSDK.shared.identityService.user?.accessID</code> value if available
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol SBLAnalyticsEventListener;

@interface SBLAnalytics (SWIFT_EXTENSION(Sensibill))
/// Adds a listener, or replaces the listener with the provided instance, if a listener with the same key already exists.
/// \param key the string used to identify the listener.
///
/// \param listener an instance of the listener
///
- (void)addListenerWithKey:(NSString * _Nonnull)key listener:(id <SBLAnalyticsEventListener> _Nonnull)listener;
/// Removes a listener with the provided key
- (void)removeListenerWithKey:(NSString * _Nonnull)key;
@end


/// Provides a flexible configuration of the appearance and behavior of Sensibill SDK.
/// In Swift, you can initialize a default object, and then replace the desired parts with custom implementaion.
/// For example:
/// \code
///      let branding = Branding()
///      branding.colors = MyCustomColors()
///      branding.fonts = MyCustomFonts()
///
/// \endcodeIn Objective-C, use <code>SBLBrandingBridge</code> to change various aspects of branding, and then use <code>convertToBranding</code> function to generate an <code>SBLBranding</code> object. Example:
/// \code
///     SBLBrandingBridge * brandingBridge = [[SBLBrandingBridge alloc]init];
///     brandingBridge.colors.primary = ...
///     brandingBridge.fonts.largeTitle = ...
///     // ...
///     SBLBrandingBridge * branding = [brandingBridge convertToBranding];
///
/// \endcodeNote that when using Objective-C, the <code>SwiftUI</code>types will be derived from the provided <code>UIKit</code> types. For example <code>Color</code> will be derived from <code>UIColor</code>.
SWIFT_CLASS_NAMED("Branding")
@interface SBLBranding : NSObject
/// Initialize the Branding with default providers
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end









@interface SBLBranding (SWIFT_EXTENSION(Sensibill))
@end

@class SBLBrandingFontDefinition;

/// The Objective-C bridge that allows to define fonts used by SDK. Corresponds to <code>BrandingFontsProvider</code> implementation in Swift.
/// <em>Note:</em> Currently only Capture fonts customization is supported in Objective-C
SWIFT_CLASS_NAMED("FontsObjCBridge")
@interface SBLBrandingFontsBridge : NSObject
/// Large Title. Default: a system font of style <code>.largeTitle</code> (default size: 34pt)
@property (nonatomic, strong) SBLBrandingFontDefinition * _Nullable largeTitle;
/// Title 2. Default: a system font of style <code>.title2</code> (default size: 22pt)
@property (nonatomic, strong) SBLBrandingFontDefinition * _Nullable title2;
/// Title 3. Default: a system font of style <code>.title3</code> (default size: 20pt)
@property (nonatomic, strong) SBLBrandingFontDefinition * _Nullable title3;
/// Body. Default: a system font of style <code>.body</code> (default size: 17pt)
@property (nonatomic, strong) SBLBrandingFontDefinition * _Nullable body;
/// Subhead. Default: a system font of style <code>.subheadline</code> (default size: 15pt)
@property (nonatomic, strong) SBLBrandingFontDefinition * _Nullable subheadline;
/// Footnote. Default: a system font of style <code>.footnote</code> (default size: 13pt)
@property (nonatomic, strong) SBLBrandingFontDefinition * _Nullable footnote;
/// Caption. Default: a system font of style <code>.caption</code> / <code>.caption1</code> (default size: 12pt)
@property (nonatomic, strong) SBLBrandingFontDefinition * _Nullable caption;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface SBLBranding (SWIFT_EXTENSION(Sensibill))
@end

@class UIImage;

/// The Objective-C bridge that allows to define icons and images used by SDK. Corresponds to <code>BrandingImagesProvider</code> implementation in Swift.
/// <em>Note:</em> Currently only Capture images and icons customization is supported in Objective-C
SWIFT_CLASS_NAMED("ImagesObjCBridge")
@interface SBLBrandingImagesBridge : NSObject
/// Capture - Common - Close icon
@property (nonatomic, strong) UIImage * _Nullable captureCloseIcon;
/// Capture - Common - Back icon
@property (nonatomic, strong) UIImage * _Nullable captureBackIcon;
/// Capture - Common - Previous page icon
@property (nonatomic, strong) UIImage * _Nullable capturePreviousPageIcon;
/// Capture - Common - Next page icon
@property (nonatomic, strong) UIImage * _Nullable captureNextPageIcon;
/// Capture - Capture Screen - Tips icon
@property (nonatomic, strong) UIImage * _Nullable captureTipsIcon;
/// Capture - Capture Screen - Auto-Capture icon - On
@property (nonatomic, strong) UIImage * _Nullable captureAutoCaptureIconOn;
/// Capture - Capture Screen - Auto-Capture icon - Off
@property (nonatomic, strong) UIImage * _Nullable captureAutoCaptureIconOff;
/// Capture - Capture Screen - Flash icon - On
@property (nonatomic, strong) UIImage * _Nullable captureFlashIconOn;
/// Capture - Capture Screen - Flash icon - Off
@property (nonatomic, strong) UIImage * _Nullable captureFlashIconOff;
/// Capture - Capture Screen - Gallery icon
@property (nonatomic, strong) UIImage * _Nullable captureGalleryIcon;
/// Capture - Capture Screen - Capture icon
@property (nonatomic, strong) UIImage * _Nullable captureCaptureIcon;
/// Capture - Tips - Close icon
@property (nonatomic, strong) UIImage * _Nullable captureTipsCloseIcon;
/// Capture - Tips - Flaten tip
@property (nonatomic, strong) UIImage * _Nullable captureTipsFlatenIcon;
/// Capture - Tips - Hold Steady tip
@property (nonatomic, strong) UIImage * _Nullable captureTipsSteadyIcon;
/// Capture - Tips - Image Brightness tip
@property (nonatomic, strong) UIImage * _Nullable captureTipsBrightIcon;
/// Capture - Tips - Long Receipt tip
@property (nonatomic, strong) UIImage * _Nullable captureTipsLongIcon;
/// Capture - Preview - Add Page icon
@property (nonatomic, strong) UIImage * _Nullable capturePreviewAddPageIcon;
/// Capture - Preview - Retake icon
@property (nonatomic, strong) UIImage * _Nullable capturePreviewRetakeIcon;
/// Capture - Preview - Discard icon
@property (nonatomic, strong) UIImage * _Nullable capturePreviewDiscardIcon;
/// Capture - Preview - Crop icon
@property (nonatomic, strong) UIImage * _Nullable capturePreviewCropIcon;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface SBLBranding (SWIFT_EXTENSION(Sensibill))
@end

@class SBLBrandingColorsBridge;

/// The Objective-C bridge for <code>SBLBranding</code>
SWIFT_CLASS_NAMED("ObjCBridge")
@interface SBLBrandingBridge : NSObject
/// Defines the fonts to be used. By default uses system font.
@property (nonatomic, strong) SBLBrandingFontsBridge * _Nonnull fonts;
/// Defines the colors to be used. By default uses the Sensibill colors
@property (nonatomic, strong) SBLBrandingColorsBridge * _Nonnull colors;
/// Defines the images to be used (e.g. for icons). By default uses system images, and some Sensibill-provided images
@property (nonatomic, strong) SBLBrandingImagesBridge * _Nonnull images;
/// Initialize the bridge.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface SBLBranding (SWIFT_EXTENSION(Sensibill))
@end

@class NSBundle;

/// The Objective-C bridge that allows to define resources used by SDK. Corresponds to <code>Branding.Resources</code>
SWIFT_CLASS_NAMED("ResourcesObjCBridge")
@interface SBLBrandingResourcesBridge : NSObject
/// Allows to provide a custom bundle to override existing localization strings, and provide localization for additional languages.
/// If the <code>localizationBundle</code> is specified, the SDK will first check for localization string in the provided <code>localizationBundle</code>
/// If the <code>localizationBundle</code> was not specified, or doesn’t contain a specific localization string, the default SDK localization string will be used.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) NSBundle * _Nullable localizationBundle;)
+ (NSBundle * _Nullable)localizationBundle SWIFT_WARN_UNUSED_RESULT;
+ (void)setLocalizationBundle:(NSBundle * _Nullable)newValue;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface SBLBranding (SWIFT_EXTENSION(Sensibill))
@end

@class UIFont;

/// Encapsulates font definition for branding
SWIFT_CLASS_NAMED("FontDefinition")
@interface SBLBrandingFontDefinition : NSObject
/// The font for usage with UIKit components
@property (nonatomic, strong) UIFont * _Nonnull uiFont;
/// initializes the font definition, based on provided custom font name, size and style
/// \param name the name of the custom font. The name must incorporate both the font family name and the specific style information for the font.
///
/// \param size the size of font in points. This value must be greater than 0.0.
///
/// \param style the <code>TextStyle</code> to scale relatively to. The value is used to construct <code>uiFont</code>, and is converted to <code>Font.TextStyle</code> to construct <code>font</code> property. Later the value is used for <code>uiFont</code> when accessibility adjustments are required.
///
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name size:(CGFloat)size style:(UIFontTextStyle _Nonnull)style;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@interface SBLBranding (SWIFT_EXTENSION(Sensibill))
@end

@class UIColor;

/// The Objective-C bridge that allows to define colors used by SDK. Corresponds to <code>BrandingColorsProvider</code> implementation in Swift.
SWIFT_CLASS_NAMED("ColorsObjCBridge")
@interface SBLBrandingColorsBridge : NSObject
/// A neutral color used for background of the views. Default: <code>#d9e1e6</code>
@property (nonatomic, strong) UIColor * _Nullable background;
/// Non-actionable text and graphics shown on <code>background</code>. Default: <code>#141414</code>
/// <ul>
///   <li>
///     Must have a 3:1 contrast ratio with <code>background</code> (WGAC 2.1)
///   </li>
///   <li>
///     Recommended to have less contrast with <code>background</code> than <code>focus</code>
///   </li>
/// </ul>
@property (nonatomic, strong) UIColor * _Nullable onBackground;
/// The primary brand color. Default: <code>#0079C1</code>
/// <ul>
///   <li>
///     Must stand out on <code>background</code>
///   </li>
///   <li>
///     Must stand out on Capture screens background (<code>black</code> by default)
///   </li>
/// </ul>
@property (nonatomic, strong) UIColor * _Nullable primary;
/// A lighter or a darker variant of the <code>primary</code> color. Default: <code>#003d61</code>
/// <ul>
///   <li>
///     Used as a background of the primary action button.
///   </li>
///   <li>
///     Must be similar in lightness to <code>primary</code>
///   </li>
/// </ul>
@property (nonatomic, strong) UIColor * _Nullable primaryVariant;
/// Text and graphics on<code>primary</code> and <code>primaryVariant</code> colors. Default: <code>#FFFFFF</code>
/// <ul>
///   <li>
///     Must have a 3:1 contrast ratio with <code>primary</code> and <code>primaryVariant</code> colors (WGAC 2.1)
///   </li>
/// </ul>
@property (nonatomic, strong) UIColor * _Nullable onPrimary;
/// The secondary brand color. Default: <code>#b3c2cc</code>
/// <ul>
///   <li>
///     Must stand out on Capture screens background (<code>black</code> by default)
///   </li>
///   <li>
///     Recommended to have less contrast than <code>primary</code> on Capture screens background (<code>black</code> by default)
///   </li>
/// </ul>
@property (nonatomic, strong) UIColor * _Nullable secondary;
/// Text and graphics on<code>secondary</code> color. Default: <code>#141414</code>
/// <ul>
///   <li>
///     Must have a 3:1 contrast ratio with <code>secondary</code>
///   </li>
/// </ul>
@property (nonatomic, strong) UIColor * _Nullable onSecondary;
/// Defines the color of surfaces of components, such as cards, sheets, and menus. Default: <code>#ffffff</code>
/// <ul>
///   <li>
///     Must be visible on <code>background</code>
///   </li>
///   <li>
///     Recommended to define as a lighter or darker variation of the <code>background</code> color.
///   </li>
/// </ul>
@property (nonatomic, strong) UIColor * _Nullable surface;
/// An accent background on top of <code>surface</code>. Default: <code>#e8f5fc</code>
/// <ul>
///   <li>
///     Must be a close (lighter or darker) variation of the <code>surface</code> color.
///   </li>
/// </ul>
@property (nonatomic, strong) UIColor * _Nullable surfaceVariant;
/// Non-actionable text and graphics on top of <code>surface</code>or <code>surfaceVariant</code>  colors. Default: <code>#4d4d4d</code>
/// <ul>
///   <li>
///     Must have a 3:1 contrast ratio with <code>surface</code> and <code>surfaceVariant</code> (WGAC 2.1)
///   </li>
///   <li>
///     Recommended to have less contrast with <code>surface</code>/  <code>surfaceVariant</code> than <code>focus</code>
///   </li>
/// </ul>
@property (nonatomic, strong) UIColor * _Nullable onSurface;
/// Actionable items and important graphics to help focus user’s attention on. May be displayed on <code>background</code>, <code>surface</code>, or <code>surfaceVariant</code>. Default: <code>#1c91d6</code>
/// <ul>
///   <li>
///     Must have a 3:1 contrast ratio with <code>background</code>, <code>surface</code>, and <code>surfaceVariant</code> colors (WGAC 2.1)
///   </li>
/// </ul>
@property (nonatomic, strong) UIColor * _Nullable focus;
/// The color or the error messages. May be displayed on <code>background</code>, <code>surface</code>, or <code>surfaceVariant</code>. Default: <code>#C30000</code>
/// <ul>
///   <li>
///     Must have a 3:1 contrast ratio with <code>background</code>, <code>surface</code>, and <code>surfaceVariant</code> colors (WGAC 2.1)
///   </li>
/// </ul>
@property (nonatomic, strong) UIColor * _Nullable error;
/// The color of background on Capture’s screen related to taking and editing the image. Default: <code>.black</code>
@property (nonatomic, strong) UIColor * _Nullable captureBackground;
/// The color of foreground on Capture’s screen related to taking and editing the image. Default: <code>.white</code>
@property (nonatomic, strong) UIColor * _Nullable onCaptureBackground;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end
















@class SBLCaptureFlowCoordinator;
@class SBLCaptureFlowProcessingInfo;

/// A protocol that defines the methods to respond to Capture Flow Coordinator events.
SWIFT_PROTOCOL_NAMED("CaptureFlowCoordinatorDelegate")
@protocol SBLCaptureFlowCoordinatorDelegate <NSObject>
@optional
/// Informs that the capture flow is about to be shown.
/// \param coordinator coordinator responsible for handling receipt capture and processing flow.
///
- (void)coordinatorWillBeginCapture:(SBLCaptureFlowCoordinator * _Nonnull)coordinator;
@required
/// Informs that a user has finished capturing document(s).
/// \param coordinator coordinator managing document capture and process flow.
///
/// \param result result containing 1 or more sourceIds of the captured document and submitted for processing.
///
- (void)coordinatorDidFinishCapture:(SBLCaptureFlowCoordinator * _Nonnull)coordinator result:(SBLCaptureFlowProcessingInfo * _Nonnull)result;
/// Informs that a user cancelled capture flow.
/// Event would be triggered if user cancels onboarding flow for the first time otherwise user explicitly taps on cancel button on capture screen.
/// \param coordinator coordinator responsible for handling receipt capture and processing flow.
///
- (void)coordinatorDidCancelCapture:(SBLCaptureFlowCoordinator * _Nonnull)coordinator;
@end

@class SBLCaptureNavigationController;
@class SBLCaptureResult;

/// A protocol that defines the methods to respond to Capture Navigation Controller events.
SWIFT_PROTOCOL_NAMED("CaptureNavigationControllerDelegate")
@protocol SBLCaptureNavigationControllerDelegate
/// Informs a delegate that capture flow has finished.
/// \param controller instance of navigation controller used for capture.
///
/// \param result instance of <code>CaptureResult</code> with an array of images produced by a capture. If no images were produced (e.g. user cancelled the capture), the result will contain an empty array of images.
///
- (void)captureNavigationController:(SBLCaptureNavigationController * _Nonnull)controller didFinishCapture:(SBLCaptureResult * _Nonnull)result;
@end


@class NSData;

/// Represents capture completion result provided via <code>CaptureNavigationControllerDelegate</code> method.
SWIFT_CLASS_NAMED("CompletionResult")
@interface SBLCaptureResult : NSObject
/// Returns captured images as a data in JPEG format. If no images were captured, an empty array will be returned.
/// The provided data can be displayed as an image using <code>UIImage(data: Data)</code>,
/// or stored in a file using <code>Data.write(to: URL, options: Data.WritingOptions)</code>.
/// You can also use <code>Data.metadata</code> and <code>Data.getLocation()</code> to retrieve an EXIF data available in the image.
@property (nonatomic, readonly, copy) NSArray<NSData *> * _Nonnull images;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface SBLCaptureResult (SWIFT_EXTENSION(Sensibill))
/// Returns <code>true</code> if the result contains no images (e.g. user cancelled the capture)
@property (nonatomic, readonly) BOOL isEmpty;
@end


@class SBLCaptureFeatureFlags;

SWIFT_CLASS_NAMED("Configuration")
@interface SBLSDKConfiguration : NSObject
/// Defines the branding used in Sensibill SDK.
@property (nonatomic, readonly, strong) SBLBranding * _Nonnull branding;
/// Defines Capture configuration
@property (nonatomic, readonly, strong) SBLCaptureFeatureFlags * _Nonnull captureFeatureFlags;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum SBLEnvironmentBridge : NSInteger;

@interface SBLSDKConfiguration (SWIFT_EXTENSION(Sensibill))
/// Initialize Sensibill SDK configuration for the provided environment, and with optional custom branding and Capture feature flags
/// For use with Objective-C only. Use <code>init(environment:branding:captureFeatureFlags)</code> with Swift.
- (nonnull instancetype)initWithEnvironmentBridgeValue:(enum SBLEnvironmentBridge)environmentBridgeValue branding:(SBLBranding * _Nonnull)branding captureFeatureFlags:(SBLCaptureFeatureFlags * _Nonnull)captureFeatureFlags;
@end

@class UIViewController;

/// Captures document images and submits them for processing to Sensibill API.
SWIFT_CLASS_NAMED("Coordinator")
@interface SBLCaptureFlowCoordinator : NSObject
/// Receives one or more event associated with document capturing and processing.
@property (nonatomic, weak) id <SBLCaptureFlowCoordinatorDelegate> _Nullable delegate;
/// Initialize a capture flow coordinator with provided <code>UIViewController</code>
/// \param host Instance of <code>UIViewController</code> on which coordinator would present receipt capture flow in full screen mode.
///
/// \param branding The branding to be provided to the capture
///
/// \param captureFeatureFlags The Capture feature flags to be passed to the capture
///
- (nonnull instancetype)initWithHost:(UIViewController * _Nonnull)host branding:(SBLBranding * _Nonnull)branding captureFeatureFlags:(SBLCaptureFeatureFlags * _Nonnull)captureFeatureFlags;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class SBLCaptureFlowDocumentMetadata;

@interface SBLCaptureFlowCoordinator (SWIFT_EXTENSION(Sensibill))
/// Start capture flow.
- (void)start;
/// Start document capture flow with specified metadata.
/// <em>Only for use when client is configured to use Sensibill API version 2</em>
/// \param metadata Instance of <code>DocumentMetadata</code>
///
- (void)startWithMetadata:(SBLCaptureFlowDocumentMetadata * _Nonnull)metadata;
@end







@class NSCoder;

/// Allows to provide the information about the documents Capture Flow will be capturing
/// In Swift, can be used directly or via the <code>DocumentMetadata.Builder</code>
/// In Objective-C, use <code>SBLCaptureFlowDocumentMetadataBuilder</code> to build the <code>SBLCaptureFlowDocumentMetadata</code>
SWIFT_CLASS_NAMED("DocumentMetadata")
@interface SBLCaptureFlowDocumentMetadata : NSObject <NSSecureCoding>
/// See: <code>NSSecureCoding</code>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL supportsSecureCoding;)
+ (BOOL)supportsSecureCoding SWIFT_WARN_UNUSED_RESULT;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface SBLCaptureFlowDocumentMetadata (SWIFT_EXTENSION(Sensibill))
@end


/// Provides a convenience interface for building <code>DocumentMetadata</code>
SWIFT_CLASS_NAMED("Builder")
@interface SBLCaptureFlowDocumentMetadataBuilder : NSObject
/// Initializes the builder, specifying if the provided document is a receipt.
- (nonnull instancetype)initForReceipt:(BOOL)forReceipt;
/// Add document description.
- (SBLCaptureFlowDocumentMetadataBuilder * _Nonnull)addWithDocumentDescription:(NSString * _Nullable)documentDescription SWIFT_WARN_UNUSED_RESULT;
/// Add account number.
- (SBLCaptureFlowDocumentMetadataBuilder * _Nonnull)addWithAccountNumber:(NSString * _Nullable)accountNumber SWIFT_WARN_UNUSED_RESULT;
/// Add account transaction ID.
- (SBLCaptureFlowDocumentMetadataBuilder * _Nonnull)addWithAccountTransactionID:(NSString * _Nullable)accountTransactionID SWIFT_WARN_UNUSED_RESULT;
/// Build document metadata object.
- (SBLCaptureFlowDocumentMetadata * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





/// Configurable Capture features and options.
/// In Swift, you can use the <code>default</code> instance to initialize the flags, and then replace the desired values with the custom ones. Example:
/// \code
///     let features: Capture.FeatureFlags = .default
///     features.defaultToAutoCapture = false
///
/// \endcodeIn Objective-C, use <code>SBLCaptureFeatureFlagsBridge</code> to provide desired options, and then convert . Example:
/// \code
///     SBLCaptureFeatureFlagsBridge *featureFlagsBridge = [[SBLCaptureFeatureFlagsBridge alloc]init];
///     featureFlagsBridge.defaultToAutoCapture = FALSE;
///     // ...
///     SBLCaptureFeatureFlags * features = [featureFlagsBridge convertToFeatureFlags];
///
/// \endcode
SWIFT_CLASS_NAMED("FeatureFlags")
@interface SBLCaptureFeatureFlags : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface SBLCaptureFeatureFlags (SWIFT_EXTENSION(Sensibill))
@end

@class NSNumber;

/// The Objective-C bridge for <code>Capture.FeatureFlags</code>
SWIFT_CLASS_NAMED("ObjCBridge")
@interface SBLCaptureFeatureFlagsBridge : NSObject
/// Allows to attach the device’s current location to the captured image. When set to <code>true</code>, the user must grant a location permission before launching capture. Default: <code>false</code>
@property (nonatomic, strong) NSNumber * _Nullable attachLocationData;
/// Compress capture result to compatible with Sensibill API. Default: <code>true</code>
@property (nonatomic, strong) NSNumber * _Nullable compressForSensibillApi;
/// Starts the capture screen with auto-capture mode enabled by default. Default: <code>true</code>
@property (nonatomic, strong) NSNumber * _Nullable defaultToAutoCapture;
/// Enables the auto-capture feature. Default: <code>true</code>
@property (nonatomic, strong) NSNumber * _Nullable enableAutoCapture;
/// Provides a warning on the preview screen if the image is blurry. Default: <code>true</code>
@property (nonatomic, strong) NSNumber * _Nullable enableBlurDetection;
/// Enables the visibility of feedback label utilized to show various capturing receipt state for user. Default: <code>true</code>
@property (nonatomic, strong) NSNumber * _Nullable enableCaptureProgressFeedback;
/// Enables the ability to crop captured images. Default: <code>true</code>
@property (nonatomic, strong) NSNumber * _Nullable enableCrop;
/// Enables the ability to toggle the device’s flash on/off to help capture in low-light situations. Default: <code>true</code>
@property (nonatomic, strong) NSNumber * _Nullable enableFlash;
/// Enables the user to select an image from their phone’s image gallery. Default: <code>true</code>
@property (nonatomic, strong) NSNumber * _Nullable enableImageGallery;
/// Enables the feedback toast on long receipt capture screen. Default: <code>true</code>
@property (nonatomic, strong) NSNumber * _Nullable enableLongReceiptPageToast;
/// Enables the long receipt capture feature - capturing a long receipt with a top and bottom image. Default: <code>true</code>
@property (nonatomic, strong) NSNumber * _Nullable enableLongCapture;
/// Enables the ability to show capture tips screen. Default: <code>true</code>
@property (nonatomic, strong) NSNumber * _Nullable enableCaptureTips;
/// Enables the integrator to define number of image(s) the user can capture and/or select in single capture session. Default: 1. Valid Range: (1, 10).
/// Value when set to more than 1 will enable adding multiple image during single capture session.
@property (nonatomic, strong) NSNumber * _Nullable maxImages;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end







@class CLLocation;

@interface NSData (SWIFT_EXTENSION(Sensibill))
/// Returns the image EXIF metadata. For use with Objective-C only. Use <code>Data</code>’s property with the same name in Swift.
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nullable metadata;
/// Returns the GPS coordinates from an image’s EXIF data, if available. For use with Objective-C only. Use <code>Data</code>’s function with the same name in Swift.
- (CLLocation * _Nullable)getLocation SWIFT_WARN_UNUSED_RESULT;
@end








@interface SBLCaptureFeatureFlagsBridge (SWIFT_EXTENSION(Sensibill))
/// Convert the provided bridge properties to the <code>SBLCaptureFeatureFlags</code>
/// <em>Note</em>: the defaults will be set automatically for the flags that ere not provided, only change the flags you’d like the non-default value for.
- (SBLCaptureFeatureFlags * _Nonnull)convertToFeatureFlags SWIFT_WARN_UNUSED_RESULT;
@end



@interface SBLBrandingBridge (SWIFT_EXTENSION(Sensibill))
/// Convert the provided bridge properties to the <code>SBLBranding</code>
/// <em>Note</em>: the defaults will be set automatically for the flags that ere not provided, only change the flags you’d like the non-default value for.
- (SBLBranding * _Nonnull)convertToBranding SWIFT_WARN_UNUSED_RESULT;
@end






/// Runtime settings of the Capture, which configures many details of capture appearance and behavior, beyond the general rules defined in <code>Branding</code>.
SWIFT_CLASS_NAMED("RuntimeSettings")
@interface SBLCaptureRuntimeSettings : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface SBLCaptureRuntimeSettings (SWIFT_EXTENSION(Sensibill))
/// Provides <code>RuntimeSettings</code> for capturing receipts. This is the default, most basic configuration.
+ (SBLCaptureRuntimeSettings * _Nonnull)receiptWithBranding:(SBLBranding * _Nullable)branding featureFlags:(SBLCaptureFeatureFlags * _Nonnull)featureFlags SWIFT_WARN_UNUSED_RESULT;
/// Provides <code>RuntimeSettings</code> for capturing an invoices. In this configuration the <code>enableLongCapture</code> feature is not available.
+ (SBLCaptureRuntimeSettings * _Nonnull)invoiceWithBranding:(SBLBranding * _Nullable)branding featureFlags:(SBLCaptureFeatureFlags * _Nonnull)featureFlags SWIFT_WARN_UNUSED_RESULT;
@end

@class UINavigationController;

/// The type responsible for notifying the consumer of Spend Manager UI about various events
SWIFT_PROTOCOL("_TtP9Sensibill20SMUIProviderDelegate_")
@protocol SMUIProviderDelegate
/// Informs that Web UI was started, and provides the reference to a presented modal or embedded <code>UINavigationController</code>.
- (void)didStartWithNavigationController:(UINavigationController * _Nonnull)navigationController;
/// Informs that Web UI was started, and provides the reference to a pushed <code>UIViewController</code>.
- (void)didStartWithViewController:(UIViewController * _Nonnull)viewController;
/// Informs that Web UI will be restarted
- (void)willRestart;
/// Informs that Web UI will be terminated
- (void)willTerminate;
/// Informs that Web UI was terminated
- (void)didTerminate;
/// Informs that Web UI initiated a Capture flow UI
- (void)willStartCaptureFlow;
/// Informs that Capture flow UI was started
- (void)didStartCaptureFlow;
/// Informs that user finished the Capture flow. Provides the result as boolean: <code>true</code> id image(s) were captured,<code>false</code> otherwise
- (void)didFinishCaptureWithImages:(BOOL)withImages;
@end

@class SBLUIProvider;

/// The Sensibill SDK entry point. See Spend Manager SDK > Get Started for more information
SWIFT_CLASS("_TtC9Sensibill12SensibillSDK")
@interface SensibillSDK : NSObject
/// Singleton Instance of the Sensibill Class
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) SensibillSDK * _Nonnull shared;)
+ (SensibillSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Allows to instantiate the Web UI for current SDK instance
@property (nonatomic, readonly, strong) SBLUIProvider * _Nonnull smui;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@interface SensibillSDK (SWIFT_EXTENSION(Sensibill))
@end


/// Defines the credentials to access API.
SWIFT_CLASS_NAMED("Credentials")
@interface SBLCredentials : NSObject <NSSecureCoding>
/// See: <code>NSSecureCoding</code>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) BOOL supportsSecureCoding;)
+ (BOOL)supportsSecureCoding SWIFT_WARN_UNUSED_RESULT;
/// OAuth 2.0 Access Token
@property (nonatomic, copy) NSString * _Nullable accessToken;
/// OAuth 2.0 Refresh Token
@property (nonatomic, copy) NSString * _Nullable refreshToken;
/// Instantiates credential object.
/// \param accessToken the access token.
///
/// \param refreshToken the refresh token.
///
- (nullable instancetype)initWithAccessToken:(NSString * _Nullable)accessToken refreshToken:(NSString * _Nullable)refreshToken OBJC_DESIGNATED_INITIALIZER;
/// See: <code>NSSecureCoding</code>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder;
/// See: <code>NSSecureCoding</code>
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface SensibillSDK (SWIFT_EXTENSION(Sensibill))
@end



@interface SensibillSDK (SWIFT_EXTENSION(Sensibill))
@end

/// Provides Objective-C bridge for <code>SensibillSDK.Environment</code>
typedef SWIFT_ENUM_NAMED(NSInteger, SBLEnvironmentBridge, "EnvironmentBridge", open) {
/// The Production environment (<code>receipts.getsensibill.com</code>)
  SBLEnvironmentBridgeProduction = 0,
/// The non-production Sandbox environment (<code>receipts-sandbox.sensibill.io</code>)
  SBLEnvironmentBridgeSandbox = 1,
/// The non-production Beta environment (<code>beta.getsensibill.com</code>)
  SBLEnvironmentBridgeBeta = 2,
};











@interface SensibillSDK (SWIFT_EXTENSION(Sensibill))
@end






@protocol SBLTokenProvider;

@interface SensibillSDK (SWIFT_EXTENSION(Sensibill))
/// <em>For usage with Objective-C only</em>.
/// With Swift, use <code>start</code> with a <code>Result<Void, Error></code> in completion, or <code>start async</code>
/// Request to start SDK. Note that this is an asynchronous operation. Caller must wait for callback to return and succeed before attempting any further interaction with SDK.
/// \param userIdentifier Unique user identifier for each user identity. A user identifier for the same user should not change from session to session.
///
/// \param tokenProvider Type conforming to <code>TokenProvider</code> responsible for retrieving user access token and (optionally) refresh tokens when requested by SDK.
///
/// \param configuration The configuration to be used for this session
///
/// \param completion a block to be called after SDK has started.
///
+ (void)startWithUserIdentifier:(NSString * _Nonnull)userIdentifier tokenProvider:(id <SBLTokenProvider> _Nonnull)tokenProvider configuration:(SBLSDKConfiguration * _Nonnull)configuration completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
/// <em>For usage with Objective-C only</em>.
/// With Swift, use <code>stop</code> with a <code>Result<Void, Error></code> in completion, or <code>stop async</code>
/// Requests to stop the SDK. Note that this is an asynchronous operation. Caller must wait for callback to return before attempting any further interaction with SDK.
/// If called during start, will stop the SDK whenever possible and will return <code>startWasInterrupted</code> error in start callback.
/// \param invalidateToken Allows to specify if user token must be invalidated. Set to <code>false</code> to prevent invalidating the token. Default: <code>true</code>
///
/// \param completion a block to be called after SDK was stopped
///
+ (void)stopWithInvalidateToken:(BOOL)invalidateToken completion:(void (^ _Nonnull)(NSError * _Nullable))completion;
@end




@interface SensibillSDK (SWIFT_EXTENSION(Sensibill))
/// Provides the SDK version
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable sdkVersion;)
+ (NSString * _Nullable)sdkVersion SWIFT_WARN_UNUSED_RESULT;
/// Provides the SDK build
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nullable sdkBuild;)
+ (NSString * _Nullable)sdkBuild SWIFT_WARN_UNUSED_RESULT;
@end



/// A protocol that defines the methods to respond to Sensibill SDK Analytics events.
SWIFT_PROTOCOL_NAMED("SensibillSDKAnalyticsEventListener")
@protocol SBLAnalyticsEventListener
/// A notification when <code>TrackingEvent</code> is received
/// \param event the <code>TrackingEvent</code> object received
///
- (void)onSensibillEvent:(SBLAnalyticsTrackingEvent * _Nonnull)event;
@end


/// A protocol that defines the methods to respond to Sensibill SDK authentication token management events.
SWIFT_PROTOCOL_NAMED("TokenProvider")
@protocol SBLTokenProvider
/// A method that provides the new credentials: access and (optionally) refresh tokens. SDK will call this method when the current access token is no longer valid.
/// note:
///
/// <ul>
///   <li>
///     SDK will cache the provided credentials, and will only call this method when they become invalid. Therefore, <em>avoid returning a cached token</em>, retrieve a fresh token from your integration server instead.
///   </li>
///   <li>
///     <em>SDK expects the <code>completion</code> block to be executed in all cases</em>:
///     <ul>
///       <li>
///         Upon successful completion ensure the <code>Credentials</code> object with the new access token (and optionally a refresh token) is passed to a completion block. The error must remain nil in this case. Example: <code>completion(credentials, nil).</code>
///       </li>
///       <li>
///         If token retrieval failed, pass an <code>Error</code> object to the completion, and pass the <code>Credentials</code> as nil. Example: <code>completion(nil, MyErrors.tokenRetrievalFailed)</code>
///       </li>
///     </ul>
///   </li>
/// </ul>
/// \param userIdentifier The identifier of the user for whom the token is requested.
///
/// \param completion A block the caller expects to be executed upon token retrieval completion.
///
- (void)provideTokenReplacementWithUserIdentifier:(NSString * _Nonnull)userIdentifier completion:(void (^ _Nonnull)(SBLCredentials * _Nullable, NSError * _Nullable))completion;
@end



@interface SBLAnalyticsTrackingEvent (SWIFT_EXTENSION(Sensibill))
/// Returns an instance of the event with provided name.
+ (SBLAnalyticsTrackingEvent * _Nonnull)eventWithName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
@end




@interface SBLAnalyticsTrackingEvent (SWIFT_EXTENSION(Sensibill))
/// The detailed description of the event
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


@interface SBLAnalyticsTrackingEvent (SWIFT_EXTENSION(Sensibill))
- (id _Nullable)objectForKeyedSubscript:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (void)setObject:(id _Nullable)newValue forKeyedSubscript:(NSString * _Nonnull)name;
/// Feature of the event
@property (nonatomic, copy) NSString * _Nullable feature;
/// Name of the event
@property (nonatomic, copy) NSString * _Nullable name;
/// Category of the event
@property (nonatomic, copy) NSString * _Nullable category;
/// Action that triggered event
@property (nonatomic, copy) NSString * _Nullable action;
/// The area of the UI where the event took place
@property (nonatomic, copy) NSString * _Nullable screenName;
/// A numeric value associated with the event
@property (nonatomic, strong) NSNumber * _Nullable value;
/// The name of the user associated with the event
@property (nonatomic, copy) NSString * _Nullable userId;
@end


























/// Defines Spend Manager UI entry points for SwiftUI and UIKit apps
SWIFT_CLASS_NAMED("UIProvider")
@interface SBLUIProvider : NSObject
/// A delegate that will receive <code>SMUI.UIProvider</code> events
@property (nonatomic, weak) id <SMUIProviderDelegate> _Nullable delegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface SBLUIProvider (SWIFT_EXTENSION(Sensibill))
@end

@class UIMenu;

/// Properties for modal presentation style
SWIFT_CLASS("_TtCCC9Sensibill4SMUI10UIProvider15ModalProperties")
@interface ModalProperties : NSObject
/// Initializes properties for modal presnetation style
/// \param presentationStyle a <code>UIModalPresentationStyle</code> to use for the modal. Optional. Default: <code>.fullScreen</code>
///
/// \param showLeftNavigationItem whether to show the left navigation item. Default: <code>false</code>. The item itself is not configurable: it’s always a Close button with <code>commonExitButtonUIKit</code> icon.
///
/// \param rightNavigationItemMenu the function that returns a menu to show in the right navigation item. Default: <code>nil</code>. Menu is always hidden, if no function is provided. But function can also control menu button appearance: if it returns <code>nil</code> instead of <code>UIMenu</code>, the button will be hidden. The icon can be configured by changing <code>commonMenuButtonUIKit</code>
///
- (nonnull instancetype)initWithPresentationStyle:(UIModalPresentationStyle)presentationStyle showLeftNavigationItem:(BOOL)showLeftNavigationItem rightNavigationItemMenu:(UIMenu * _Nullable (^ _Nullable)(void))rightNavigationItemMenu OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@interface SBLUIProvider (SWIFT_EXTENSION(Sensibill))
@end


/// <em>For usage with Objective-C</em>. With Swift, <code>NavigationIntent</code>.
/// Represents supported Sensibill UI navigation intents.
SWIFT_CLASS_NAMED("NavigationIntentObjCBridge")
@interface SBLNavigationIntentBridge : NSObject
/// Initialize the
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// The homepage dashboard.
- (void)dashboard;
/// Displays a list of all receipts.
- (void)receiptList;
/// Displays details of the receipt with the provided ID.
- (void)receiptDetailsWithId:(NSString * _Nonnull)id;
/// Displays a list of user-created folders.
- (void)folderList;
/// Displays an individual folder with the provided ID.
- (void)folderDetailsWithId:(NSString * _Nonnull)id;
/// Displays a list of exports the user had requested.
- (void)exportList;
/// Displays a Tips page
- (void)tips;
/// Displays an Achievements page.
- (void)achievements;
/// Displays a metadata edit page for a provided list of localIds. The list of local IDs should be retrieved from the Transaction objects submitted for processing.
- (void)metadataEditWithLocalIds:(NSArray<NSString *> * _Nonnull)localIds;
@end


@interface SBLUIProvider (SWIFT_EXTENSION(Sensibill))
/// <em>For usage with Objective-C</em>.
/// With Swift, use <code>start(modalOver:navigationIntent:animated:modalProperties)</code>.
/// Start Sensibill UI as a full-screen modal over the provided host
/// \param host the <code>UIViewController</code> over which the Sensibill UI will be presented. Required.
///
/// \param navigationIntentBridge the initial page to start UI on. Default: <code>.dashboard</code>
///
/// \param animated whether the view should be animated when presented. Does not apply to <code>.embed</code> presentation method. Optional. Default: <code>false</code>.
///
/// \param modalProperties the properties to use with the modal. Default: <code>.fullScreen</code>, without navigation buttons.
///
- (void)startModalWithHost:(UIViewController * _Nonnull)host navigationIntentBridge:(SBLNavigationIntentBridge * _Nonnull)navigationIntentBridge animated:(BOOL)animated modalProperties:(ModalProperties * _Nonnull)modalProperties;
/// <em>For usage with Objective-C</em>.
/// With Swift, use <code>start(embedIn:navigationIntent)</code>.
/// Embeds Sensibill UI into a provided host
/// \param host the <code>UIViewController</code> over which the Sensibill UI will be presented. Required.
///
/// \param navigationIntentBridge the initial page to start UI on. Default: <code>.dashboard</code>
///
- (void)startEmbeddedWithHost:(UIViewController * _Nonnull)host navigationIntentBridge:(SBLNavigationIntentBridge * _Nonnull)navigationIntentBridge;
/// <em>For usage with Objective-C</em>.
/// With Swift, use <code>start(pushTo:navigationIntent:animated)</code>.
/// Pushes Sensibill UI into a provided <code>UINavigationController</code>
/// \param host the <code>UIViewController</code> over which the Sensibill UI will be presented. Required.
///
/// \param navigationIntentBridge the initial page to start UI on. Default: <code>.dashboard</code>
///
/// \param animated whether the view should be animated when presented. Does not apply to <code>.embed</code> presentation method. Default: <code>false</code>.
///
- (void)startByPushWithHost:(UINavigationController * _Nonnull)host navigationIntentBridge:(SBLNavigationIntentBridge * _Nonnull)navigationIntentBridge animated:(BOOL)animated;
@end










#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
